[project]
name = "pagemerge"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=2.2.2",
    "pillow>=11.1.0",
    "pymupdf>=1.25.2",
    "pypdf>=5.1.0",
    "ruff>=0.9.2",
]
